Importing libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('/content/imdb-top-1000.csv')
movies.head(2)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0

In [3]:
genre = movies.groupby('Genre')
genre

In [4]:
genre.std(numeric_only=True).head(2)

             Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     28.500706     0.304258  432946.814748  2.256724e+08  12.421252
Adventure  33.317320     0.229781  301188.347642  1.697543e+08  12.345393

In [5]:
genre.min().head(2)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0

In [6]:
genre.max()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Yôjinbô,2019,321,9.0,Zack Snyder,Yun-Fat Chow,2303232,936662225.0,98.0
Adventure,Zombieland,PG,228,8.6,Ömer Faruk Sorak,Yves Montand,1512360,874211619.0,100.0
Animation,Ôkami kodomo no Ame to Yuki,2020,137,8.6,Yoshifumi Kondô,Yôji Matsuda,999790,873839108.0,96.0
Biography,Zerkalo,2020,209,8.9,Tom McCarthy,Éric Toledano,1213505,753585104.0,97.0
Comedy,Zindagi Na Milegi Dobara,2020,188,8.6,Zoya Akhtar,Ömer Faruk Sorak,939631,886752933.0,99.0
Crime,À bout de souffle,2019,229,9.2,Yavuz Turgul,Vincent Cassel,1826188,790482117.0,100.0
Drama,Zwartboek,2020,242,9.3,Çagan Irmak,Çetin Tekindor,2343110,924558264.0,100.0
Family,Willy Wonka & the Chocolate Factory,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Nosferatu,1922,94,8.1,Robert Wiene,Werner Krauss,88794,445151978.0,NaN
Film-Noir,The Third Man,1949,108,8.1,John Huston,Teresa Wright,158731,123353292.0,97.0
Horror,The Thing,2017,122,8.5,William Friedkin,Sigourney Weaver,787806,298791505.0,97.0
Mystery,Vertigo,2012,138,8.4,Terry Gilliam,Vidya Balan,1129894,474203697.0,100.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,165,8.8,Sergio Leone,Henry Fonda,688390,31800000.0,90.0

In [7]:
#Gross means: the total amount of money a film generates from ticket sales at the box office before any deductions.
# find the top 3 genres by total earning
movies.groupby('Genre')['Gross'].sum().head(3)

Genre
Action       3.263226e+10
Adventure    9.496922e+09
Animation    1.463147e+10
Name: Gross, dtype: float64

In [8]:
#finding highest avg rating
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(3)

Genre
Western    8.350000
Crime      8.016822
Fantasy    8.000000
Name: IMDB_Rating, dtype: float64

In [9]:
# Director with popularity
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(3)

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
Name: No_of_Votes, dtype: int64

In [10]:
# find the highest rated movie of each genre
movies.groupby('Genre')['IMDB_Rating'].max()

Genre
Action       9.0
Adventure    8.6
Animation    8.6
Biography    8.9
Comedy       8.6
Crime        9.2
Drama        9.3
Family       7.8
Fantasy      8.1
Film-Noir    8.1
Horror       8.5
Mystery      8.4
Thriller     7.8
Western      8.8
Name: IMDB_Rating, dtype: float64

In [11]:
# find number of movies done by each actor
movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)

Star1
Tom Hanks            12
Robert De Niro       11
Clint Eastwood       10
Al Pacino            10
Leonardo DiCaprio     9
                     ..
Gérard Jugnot         1
Günes Sensoy          1
Haluk Bilginer        1
Harriet Andersson     1
Graham Chapman        1
Name: Series_Title, Length: 660, dtype: int64

In [12]:
# GroupBy Attributes and Methods
# find total number of groups -> len
# find items in each group -> size
# first()/last() -> nth item
# get_group -> vs filtering
# groups
# describe
# sample
# nunique

In [13]:
len(movies)

1000

In [14]:
movies.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [15]:
movies.groupby('Genre').first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [18]:
movies.groupby('Genre').last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [19]:
movies.groupby('Genre').nth(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
9,Fight Club,1999,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102.0,66.0
15,Goodfellas,1990,146,Biography,8.7,Martin Scorsese,Robert De Niro,1020727,46836394.0,90.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
43,The Lion King,1994,88,Animation,8.5,Roger Allers,Rob Minkoff,942045,422783777.0,88.0
47,Back to the Future,1985,116,Adventure,8.5,Robert Zemeckis,Michael J. Fox,1058081,210609762.0,87.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0

In [20]:
movies.groupby('Genre').get_group('Action')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
...,...,...,...,...,...,...,...,...,...,...
968,Falling Down,1993,113,Action,7.6,Joel Schumacher,Michael Douglas,171640,40903593.0,56.0
979,Lethal Weapon,1987,109,Action,7.6,Richard Donner,Mel Gibson,236894,65207127.0,68.0
982,Mad Max 2,1981,96,Action,7.6,George Miller,Mel Gibson,166588,12465371.0,77.0
983,The Warriors,1979,92,Action,7.6,Walter Hill,Michael Beck,93878,22490039.0,65.0
985,Escape from Alcatraz,1979,112,Action,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0

In [21]:
movies.groupby('Genre').groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [24]:
movies.groupby('Genre').describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [26]:
movies.groupby('Genre').sample(3, replace=True)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
930,Watchmen,2009,162,Action,7.6,Zack Snyder,Jackie Earle Haley,500799,107509799.0,56.0
201,Haider,2014,160,Action,8.1,Vishal Bhardwaj,Shahid Kapoor,50445,901610.0,NaN
821,The Last of the Mohicans,1992,112,Action,7.7,Michael Mann,Daniel Day-Lewis,150409,75505856.0,76.0
306,Le salaire de la peur,1953,131,Adventure,8.1,Henri-Georges Clouzot,Yves Montand,54588,124570860.0,85.0
506,Harry Potter and the Prisoner of Azkaban,2004,142,Adventure,7.9,Alfonso Cuarón,Daniel Radcliffe,552493,249358727.0,82.0
549,Spartacus,1960,197,Adventure,7.9,Stanley Kubrick,Kirk Douglas,124339,30000000.0,87.0
399,Aladdin,1992,90,Animation,8.0,Ron Clements,John Musker,373845,217350219.0,86.0
596,Toy Story 4,2019,100,Animation,7.8,Josh Cooley,Tom Hanks,203177,434038008.0,84.0
211,Ôkami kodomo no Ame to Yuki,2012,117,Animation,8.1,Mamoru Hosoda,Aoi Miyazaki,38803,224400323.0,71.0
940,Finding Neverland,2004,106,Biography,7.6,Marc Forster,Johnny Depp,198677,51680613.0,67.0
346,The King's Speech,2010,118,Biography,8.0,Tom Hooper,Colin Firth,639603,138797449.0,88.0
18,Hamilton,2020,160,Biography,8.6,Thomas Kail,Lin-Manuel Miranda,55291,440984783.0,90.0
660,The Sandlot,1993,101,Comedy,7.8,David Mickey Evans,Tom Guiry,78963,32416586.0,55.0
973,Home Alone,1990,103,Comedy,7.6,Chris Columbus,Macaulay Culkin,488817,285761243.0,63.0
327,La La Land,2016,128,Comedy,8.0,Damien Chazelle,Ryan Gosling,505918,151101803.0,94.0
519,Once Were Warriors,1994,102,Crime,7.9,Lee Tamahori,Rena Owen,31590,2201126.0,77.0
885,Victoria,2015,138,Crime,7.6,Sebastian Schipper,Laia Costa,52903,718096942.0,77.0
954,Lola rennt,1998,81,Crime,7.6,Tom Tykwer,Franka Potente,188317,7267585.0,77.0
286,Solaris,1972,167,Drama,8.1,Andrei Tarkovsky,Natalya Bondarchuk,81021,526246744.0,90.0
793,Billy Elliot,2000,110,Drama,7.7,Stephen Daldry,Jamie Bell,126770,21995263.0,74.0
67,The Lives of Others,2006,137,Drama,8.4,Florian Henckel von Donnersmarck,Ulrich Mühe,358685,11286112.0,89.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
959,Dark City,1998,100,Mystery,7.6,Alex Proyas,Rufus Sewell,187927,14378331.0,66.0
829,Spoorloos,1988,107,Mystery,7.7,George Sluizer,Bernard-Pierre Donnadieu,33982,367916835.0,NaN
714,The Lady Vanishes,1938,96,Mystery,7.8,Alfred Hitchcock,Margaret Lockwood,47400,474203697.0,98.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
691,The Outlaw Josey Wales,1976,135,Western,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [27]:
movies.groupby('Genre')['IMDB_Rating'].nunique()

Genre
Action       15
Adventure    10
Animation    11
Biography    13
Comedy       11
Crime        14
Drama        14
Family        1
Fantasy       2
Film-Noir     3
Horror        8
Mystery       8
Thriller      1
Western       4
Name: IMDB_Rating, dtype: int64

In [28]:
movies.head(2)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0

In [30]:
#Applying aggregate function{min,max,mean,std} in once
#passing dictionary
genre.agg(
    {
        'Runtime':'min',
        'Gross':'max',
        'IMDB_Rating':'mean',
        'No_of_Votes':'std'
    }
)

           Runtime        Gross  IMDB_Rating    No_of_Votes
Genre
Action          45  936662225.0     7.949419  432946.814748
Adventure       88  874211619.0     7.937500  301188.347642
Animation       71  873839108.0     7.930488  262173.231571
Biography       93  753585104.0     7.938636  271284.191372
Comedy          68  886752933.0     7.901290  188653.570564
Crime           80  790482117.0     8.016822  373999.730656
Drama           64  924558264.0     7.957439  305554.162841
Family         100  435110554.0     7.800000  137008.302816
Fantasy         76  445151978.0     8.000000   22179.111299
Film-Noir      100  123353292.0     7.966667   54649.083277
Horror          71  298791505.0     7.909091  234883.508691
Mystery         96  474203697.0     7.975000  404621.915297
Thriller       108   17550741.0     7.800000            NaN
Western        132   31800000.0     8.350000  263489.554280

In [40]:
#passing list

# Select only numeric columns from the DataFrame *before* applying the agg functions
numeric_columns_to_agg = movies.select_dtypes(include=np.number).columns

genre[numeric_columns_to_agg].agg(
    [
        'min',
        'max',
        'mean',
        'sum'
    ]
)

          Released_Year                                Runtime       \
                    min     max         mean       sum     min  max
Genre
Action           1924.0  2019.0  1997.081395  343498.0      45  321
Adventure        1925.0  2019.0  1986.450704  141038.0      88  228
Animation        1940.0  2020.0  2002.219512  164182.0      71  137
Biography        1928.0  2020.0  1998.386364  175858.0      93  209
Comedy           1921.0  2020.0  1986.554839  307916.0      68  188
Crime            1931.0  2019.0  1989.420561  212868.0      80  229
Drama            1925.0  2020.0  1988.948097  574806.0      64  242
Family           1971.0  1982.0  1976.500000    3953.0     100  115
Fantasy          1920.0  1922.0  1921.000000    3842.0      76   94
Film-Noir        1941.0  1949.0  1944.333333    5833.0     100  108
Horror           1933.0  2017.0  1977.818182   21756.0      71  122
Mystery          1938.0  2012.0  1986.166667   23834.0      96  138
Thriller         1967.0  1967.0  1967.000000    1967.0     108  108
Western          1965.0  1976.0  1968.750000    7875.0     132  165

                             IMDB_Rating       ...    No_of_Votes            \
                 mean    sum         min  max  ...           mean       sum
Genre                                          ...
Action     129.046512  22196         7.6  9.0  ...  420246.581395  72282412
Adventure  134.111111   9656         7.6  8.6  ...  313557.819444  22576163
Animation   99.585366   8166         7.6  8.6  ...  268032.073171  21978630
Biography  136.022727  11970         7.6  8.9  ...  272805.045455  24006844
Comedy     112.129032  17380         7.6  8.6  ...  178195.658065  27620327
Crime      126.392523  13524         7.6  9.2  ...  313398.271028  33533615
Drama      124.737024  36049         7.6  9.3  ...  212343.612457  61367304
Family     107.500000    215         7.8  7.8  ...  275610.500000    551221
Fantasy     85.000000    170         7.9  8.1  ...   73111.000000    146222
Film-Noir  104.000000    312         7.8  8.1  ...  122405.000000    367215
Horror     102.090909   1123         7.6  8.5  ...  340232.363636   3742556
Mystery    119.083333   1429         7.6  8.4  ...  350250.333333   4203004
Thriller   108.000000    108         7.8  7.8  ...   27733.000000     27733
Western    148.250000    593         7.8  8.8  ...  322416.250000   1289665

                 Gross                                          Metascore  \
                   min          max          mean           sum       min
Genre
Action          3296.0  936662225.0  1.897224e+08  3.263226e+10      33.0
Adventure      61001.0  874211619.0  1.319017e+08  9.496922e+09      41.0
Animation     128985.0  873839108.0  1.784326e+08  1.463147e+10      61.0
Biography      21877.0  753585104.0  9.404952e+07  8.276358e+09      48.0
Comedy          1305.0  886752933.0  1.010572e+08  1.566387e+10      45.0
Crime           6013.0  790482117.0  7.899656e+07  8.452632e+09      47.0
Drama           3600.0  924558264.0  1.225259e+08  3.540997e+10      28.0
Family       4000000.0  435110554.0  2.195553e+08  4.391106e+08      67.0
Fantasy    337574718.0  445151978.0  3.913633e+08  7.827267e+08       NaN
Film-Noir     449191.0  123353292.0  4.197018e+07  1.259105e+08      94.0
Horror         89029.0  298791505.0  9.405902e+07  1.034649e+09      46.0
Mystery      1035953.0  474203697.0  1.047014e+08  1.256417e+09      52.0
Thriller    17550741.0   17550741.0  1.755074e+07  1.755074e+07      81.0
Western      5321508.0   31800000.0  1.455538e+07  5.822151e+07      69.0


             max       mean      sum
Genre
Action      98.0  73.419580  10499.0
Adventure  100.0  78.437500   5020.0
Animation   96.0  81.093333   6082.0
Biography   97.0  76.240506   6023.0
Comedy      99.0  78.720000   9840.0
Crime      100.0  77.080460   6706.0
Drama      100.0  79.701245  19208.0
Family      91.0  79.000000    158.0
Fantasy      NaN        NaN      0.0
Film-Noir   97.0  95.666667    287.0
Horror      97.0  80.000000    880.0
Mystery    100.0  79.125000    633.0
Thriller    81.0  81.000000     81.0
Western     90.0  78.250000    313.0

[14 rows x 24 columns]

In [49]:
#loops in groups
max_rating_movies = []
for groups, data in genre:
    max_rating_movies.append(data[data['IMDB_Rating'] == data['IMDB_Rating'].max()])
df = pd.concat(max_rating_movies, ignore_index=True)
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
1,Interstellar,2014.0,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
2,Sen to Chihiro no kamikakushi,2001.0,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
3,Schindler's List,1993.0,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
4,Gisaengchung,2019.0,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
5,La vita è bella,1997.0,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
6,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
7,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
8,E.T. the Extra-Terrestrial,1982.0,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
9,Willy Wonka & the Chocolate Factory,1971.0,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
10,Das Cabinet des Dr. Caligari,1920.0,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
11,The Third Man,1949.0,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
12,Psycho,1960.0,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
13,Memento,2000.0,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
14,Rear Window,1954.0,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
15,Wait Until Dark,1967.0,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
16,"Il buono, il brutto, il cattivo",1966.0,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [51]:
#Apply function
genre.apply('min')

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924.0,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925.0,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0
Animation,Akira,1940.0,71,7.6,Adam Elliot,Adrian Molina,25229,128985.0,61.0
Biography,12 Years a Slave,1928.0,93,7.6,Adam McKay,Adrien Brody,27254,21877.0,48.0
Comedy,(500) Days of Summer,1921.0,68,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,45.0
Crime,12 Angry Men,1931.0,80,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,47.0
Drama,1917,1925.0,64,7.6,Aamir Khan,Abhay Deol,25088,3600.0,28.0
Family,E.T. the Extra-Terrestrial,1971.0,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920.0,76,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941.0,100,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933.0,71,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938.0,96,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,52.0
Thriller,Wait Until Dark,1967.0,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965.0,132,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [54]:
# find number of movies starting with A for each group
def foo(group):
  return group['Series_Title'].str.startswith('A').sum()

In [55]:
genre.apply(foo)

/tmp/ipykernel_1895/2031851770.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(foo)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [56]:
# find ranking of each movie in the group according to IMDB score
def my_rank(group):
  group['rank'] = group['IMDB_Rating'].rank(ascending=False)
  return group

In [57]:
genre.apply(my_rank)

/tmp/ipykernel_1895/1658535122.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(my_rank)

                                                   Series_Title  \
Genre
Action   2                                      The Dark Knight
         5        The Lord of the Rings: The Return of the King
         8                                            Inception
         10   The Lord of the Rings: The Fellowship of the Ring
         13               The Lord of the Rings: The Two Towers
...                                                         ...
Thriller 700                                    Wait Until Dark
Western  12                     Il buono, il brutto, il cattivo
         48                        Once Upon a Time in the West
         115                         Per qualche dollaro in più
         691                             The Outlaw Josey Wales

              Released_Year  Runtime     Genre  IMDB_Rating  \
Genre
Action   2           2008.0      152    Action          9.0
         5           2003.0      201    Action          8.9
         8           2010.0      148    Action          8.8
         10          2001.0      178    Action          8.8
         13          2002.0      179    Action          8.7
...                     ...      ...       ...          ...
Thriller 700         1967.0      108  Thriller          7.8
Western  12          1966.0      161   Western          8.8
         48          1968.0      165   Western          8.5
         115         1965.0      132   Western          8.3
         691         1976.0      135   Western          7.8

                       Director              Star1  No_of_Votes        Gross  \
Genre
Action   2    Christopher Nolan     Christian Bale      2303232  534858444.0
         5        Peter Jackson        Elijah Wood      1642758  377845905.0
         8    Christopher Nolan  Leonardo DiCaprio      2067042  292576195.0
         10       Peter Jackson        Elijah Wood      1661481  315544750.0
         13       Peter Jackson        Elijah Wood      1485555  342551365.0
...                         ...                ...          ...          ...
Thriller 700      Terence Young     Audrey Hepburn        27733   17550741.0
Western  12        Sergio Leone     Clint Eastwood       688390    6100000.0
         48        Sergio Leone        Henry Fonda       302844    5321508.0
         115       Sergio Leone     Clint Eastwood       232772   15000000.0
         691     Clint Eastwood     Clint Eastwood        65659   31800000.0

              Metascore  rank
Genre
Action   2         84.0   1.0
         5         94.0   2.0
         8         74.0   3.5
         10        92.0   3.5
         13        87.0   6.0
...                 ...   ...
Thriller 700       81.0   1.0
Western  12        90.0   1.0
         48        80.0   2.0
         115       74.0   3.0
         691       69.0   4.0

[1000 rows x 11 columns]

In [58]:
# find normalized IMDB rating group wise
def rating(groups):
  groups['norm_rat'] = (groups['IMDB_Rating'].min() / groups['IMDB_Rating'].max())
  return groups

In [59]:
genre.apply(rating)

/tmp/ipykernel_1895/266811772.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(rating)

                                                   Series_Title  \
Genre
Action   2                                      The Dark Knight
         5        The Lord of the Rings: The Return of the King
         8                                            Inception
         10   The Lord of the Rings: The Fellowship of the Ring
         13               The Lord of the Rings: The Two Towers
...                                                         ...
Thriller 700                                    Wait Until Dark
Western  12                     Il buono, il brutto, il cattivo
         48                        Once Upon a Time in the West
         115                         Per qualche dollaro in più
         691                             The Outlaw Josey Wales

              Released_Year  Runtime     Genre  IMDB_Rating  \
Genre
Action   2           2008.0      152    Action          9.0
         5           2003.0      201    Action          8.9
         8           2010.0      148    Action          8.8
         10          2001.0      178    Action          8.8
         13          2002.0      179    Action          8.7
...                     ...      ...       ...          ...
Thriller 700         1967.0      108  Thriller          7.8
Western  12          1966.0      161   Western          8.8
         48          1968.0      165   Western          8.5
         115         1965.0      132   Western          8.3
         691         1976.0      135   Western          7.8

                       Director              Star1  No_of_Votes        Gross  \
Genre
Action   2    Christopher Nolan     Christian Bale      2303232  534858444.0
         5        Peter Jackson        Elijah Wood      1642758  377845905.0
         8    Christopher Nolan  Leonardo DiCaprio      2067042  292576195.0
         10       Peter Jackson        Elijah Wood      1661481  315544750.0
         13       Peter Jackson        Elijah Wood      1485555  342551365.0
...                         ...                ...          ...          ...
Thriller 700      Terence Young     Audrey Hepburn        27733   17550741.0
Western  12        Sergio Leone     Clint Eastwood       688390    6100000.0
         48        Sergio Leone        Henry Fonda       302844    5321508.0
         115       Sergio Leone     Clint Eastwood       232772   15000000.0
         691     Clint Eastwood     Clint Eastwood        65659   31800000.0

              Metascore  norm_rat
Genre
Action   2         84.0  0.844444
         5         94.0  0.844444
         8         74.0  0.844444
         10        92.0  0.844444
         13        87.0  0.844444
...                 ...       ...
Thriller 700       81.0  1.000000
Western  12        90.0  0.886364
         48        80.0  0.886364
         115       74.0  0.886364
         691       69.0  0.886364

[1000 rows x 11 columns]

In [63]:
# groupby on multiple cols
mask = movies.groupby(['Director','Star1'])
mask.size()

Director             Star1
Aamir Khan           Amole Gupte       1
Aaron Sorkin         Eddie Redmayne    1
Abdellatif Kechiche  Léa Seydoux       1
Abhishek Chaubey     Shahid Kapoor     1
Abhishek Kapoor      Amit Sadh         1
                                      ..
Zaza Urushadze       Lembit Ulfsak     1
Zoya Akhtar          Hrithik Roshan    1
                     Vijay Varma       1
Çagan Irmak          Çetin Tekindor    1
Ömer Faruk Sorak     Cem Yilmaz        1
Length: 898, dtype: int64

In [65]:
mask.get_group(('Christopher Nolan','Christian Bale'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
36,The Prestige,2006.0,130,Drama,8.5,Christopher Nolan,Christian Bale,1190259,53089891.0,66.0
63,The Dark Knight Rises,2012.0,164,Action,8.4,Christopher Nolan,Christian Bale,1516346,448139099.0,78.0
155,Batman Begins,2005.0,140,Action,8.2,Christopher Nolan,Christian Bale,1308302,206852432.0,70.0

In [67]:
# find the most earning actor->director combo
movies.groupby(['Director', 'Star1'])['Gross'].sum().sort_values(ascending=False).head(3)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Anthony Russo   Joe Russo         2.205039e+09
Billy Wilder    William Holden    1.286779e+09
Name: Gross, dtype: float64

In [70]:
movies.groupby(['Star1','Genre'])['Metascore'].mean().reset_index().sort_values(by='Metascore', ascending=False).head(3)

             Star1      Genre  Metascore
606  Peter O'Toole  Adventure      100.0
590   Orson Welles      Drama      100.0
77     Bertil Guve      Drama      100.0

In [74]:
#Agg on multiple cols
movies['Released_Year'] = pd.to_numeric(movies['Released_Year'], errors='coerce')
mask = movies.groupby(['Director','Star1'])
numeric_cols = movies.select_dtypes(include=np.number).columns
mask[numeric_cols].agg(['min','max','mean','std'])

                                   Released_Year                     Runtime  \
                                             min     max    mean std     min
Director            Star1
Aamir Khan          Amole Gupte           2007.0  2007.0  2007.0 NaN     165
Aaron Sorkin        Eddie Redmayne        2020.0  2020.0  2020.0 NaN     129
Abdellatif Kechiche Léa Seydoux           2013.0  2013.0  2013.0 NaN     180
Abhishek Chaubey    Shahid Kapoor         2016.0  2016.0  2016.0 NaN     148
Abhishek Kapoor     Amit Sadh             2013.0  2013.0  2013.0 NaN     130
...                                          ...     ...     ...  ..     ...
Zaza Urushadze      Lembit Ulfsak         2013.0  2013.0  2013.0 NaN      87
Zoya Akhtar         Hrithik Roshan        2011.0  2011.0  2011.0 NaN     155
                    Vijay Varma           2019.0  2019.0  2019.0 NaN     154
Çagan Irmak         Çetin Tekindor        2005.0  2005.0  2005.0 NaN     112
Ömer Faruk Sorak    Cem Yilmaz            2004.0  2004.0  2004.0 NaN     127

                                                   IMDB_Rating       ...  \
                                    max   mean std         min  max  ...
Director            Star1                                            ...
Aamir Khan          Amole Gupte     165  165.0 NaN         8.4  8.4  ...
Aaron Sorkin        Eddie Redmayne  129  129.0 NaN         7.8  7.8  ...
Abdellatif Kechiche Léa Seydoux     180  180.0 NaN         7.7  7.7  ...
Abhishek Chaubey    Shahid Kapoor   148  148.0 NaN         7.8  7.8  ...
Abhishek Kapoor     Amit Sadh       130  130.0 NaN         7.7  7.7  ...
...                                 ...    ...  ..         ...  ...  ...
Zaza Urushadze      Lembit Ulfsak    87   87.0 NaN         8.2  8.2  ...
Zoya Akhtar         Hrithik Roshan  155  155.0 NaN         8.1  8.1  ...
                    Vijay Varma     154  154.0 NaN         8.0  8.0  ...
Çagan Irmak         Çetin Tekindor  112  112.0 NaN         8.3  8.3  ...
Ömer Faruk Sorak    Cem Yilmaz      127  127.0 NaN         8.0  8.0  ...

                                   No_of_Votes            Gross               \
                                          mean std          min          max
Director            Star1
Aamir Khan          Amole Gupte       168895.0 NaN    1223869.0    1223869.0
Aaron Sorkin        Eddie Redmayne     89896.0 NaN  853090410.0  853090410.0
Abdellatif Kechiche Léa Seydoux       138741.0 NaN    2199675.0    2199675.0
Abhishek Chaubey    Shahid Kapoor      27175.0 NaN  218428303.0  218428303.0
Abhishek Kapoor     Amit Sadh          32628.0 NaN    1122527.0    1122527.0
...                                        ...  ..          ...          ...
Zaza Urushadze      Lembit Ulfsak      40382.0 NaN     144501.0     144501.0
Zoya Akhtar         Hrithik Roshan     67927.0 NaN    3108485.0    3108485.0
                    Vijay Varma        31886.0 NaN    5566534.0    5566534.0
Çagan Irmak         Çetin Tekindor     78925.0 NaN  461855363.0  461855363.0
Ömer Faruk Sorak    Cem Yilmaz         56960.0 NaN  196206077.0  196206077.0

                                                    Metascore
                                           mean std       min   max  mean std
Director            Star1
Aamir Khan          Amole Gupte       1223869.0 NaN       NaN   NaN   NaN NaN
Aaron Sorkin        Eddie Redmayne  853090410.0 NaN      77.0  77.0  77.0 NaN
Abdellatif Kechiche Léa Seydoux       2199675.0 NaN      89.0  89.0  89.0 NaN
Abhishek Chaubey    Shahid Kapoor   218428303.0 NaN       NaN   NaN   NaN NaN
Abhishek Kapoor     Amit Sadh         1122527.0 NaN      40.0  40.0  40.0 NaN
...                                         ...  ..       ...   ...   ...  ..
Zaza Urushadze      Lembit Ulfsak      144501.0 NaN      73.0  73.0  73.0 NaN
Zoya Akhtar         Hrithik Roshan    3108485.0 NaN       NaN   NaN   NaN NaN
                    Vijay Varma       5566534.0 NaN      65.0  65.0  65.0 NaN
Çagan Irmak         Çetin Tekindor  461855363.0 NaN       NaN   NaN   NaN NaN
Ömer Faruk Sorak    Cem Yilmaz      196206077.0 NaN       NaN   NaN   NaN NaN

[898 rows x 24 columns]

working with ipl new dataaet

In [76]:
ipl = pd.read_csv('/content/deliveries.csv')
ipl.head(3)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [77]:
ipl.shape

(179078, 21)

In [79]:
# find the top 10 batsman in terms of runs

ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [81]:
# find the batsman with max no of sixes
sixes = ipl[ipl['batsman_runs'] == 6]
sixes.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head()

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
Name: batsman_runs, dtype: int64

In [82]:
# find V Kohli's record against all teams
temp_df = ipl[ipl['batsman'] == 'V Kohli']

temp_df.groupby('bowling_team')['batsman_runs'].sum().reset_index()

               bowling_team  batsman_runs
0       Chennai Super Kings           749
1           Deccan Chargers           306
2            Delhi Capitals            66
3          Delhi Daredevils           763
4             Gujarat Lions           283
5           Kings XI Punjab           636
6      Kochi Tuskers Kerala            50
7     Kolkata Knight Riders           675
8            Mumbai Indians           628
9             Pune Warriors           128
10         Rajasthan Royals           370
11   Rising Pune Supergiant            83
12  Rising Pune Supergiants           188
13      Sunrisers Hyderabad           509

In [83]:
# Create a function that can return the highest score of any batsman

def highest(batsman):
  temp_df = ipl[ipl['batsman'] == batsman]
  return temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]

In [84]:
highest('V Kohli')

np.int64(113)